# create description 
usethis::use_description(check_name = FALSE)
usethis::use_mit_license()
usethis::use_package("usethis")
usethis::use_package("dplyr")
usethis::use_package("readxl")
usethis::use_package("tidyr")
usethis::use_package("animation")
usethis::use_package("ggplot2")
usethis::use_package("ggpubr")
usethis::use_package("ggExtra")
usethis::use_package("patchwork")
usethis::use_package("viridis")
usethis::use_package("scales")
usethis::use_package("zoo")
usethis::use_package("gam")
usethis::use_package("lme4")
usethis::use_package("mgcv")
usethis::use_package("itsadug")
usethis::use_package("bbmle")
usethis::use_package("gratia")
usethis::use_package("gganimate")
usethis::use_package("car")
usethis::use_package("AICcmodavg")
usethis::use_package("MuMIn")
#devtools::document()
# creation d'un fichier functions.R dans R/ --
usethis::use_r("coef_calculus")
usethis::use_r("length_calculus")
usethis::use_r("PLOT")
usethis::use_r("AICtab")
utils::file.edit("analyse/01.import_data.R")
utils::file.edit("analyse/02.angular_ratio_comparison.R")
utils::file.edit("analyse/03.acceleration_distance_position_metrics.R")
utils::file.edit("analyse/04.GIF.R")
utils::file.edit("analyse/05.statistic_models_REML.R")
utils::file.edit("analyse/06.statistic_models_results.R")
utils::file.edit("analyse/07.statistic_models_ML.R")
utils::file.edit("analyse/08.GAM_table.R")
utils::file.edit("analyse/09.statistical_table_behaviour_fast_start_steady.R")
utils::file.edit("make.R")

