# create description 
usethis::use_description(check_name = FALSE)
usethis::use_mit_license()
usethis::use_package("usethis")
usethis::use_package("readxl")
usethis::use_package("dplyr")
usethis::use_package("readr")
usethis::use_package("hexbin")
usethis::use_package("GGally")
usethis::use_package("ggplot2")
usethis::use_package("gganimate")
usethis::use_package("randomForest")
usethis::use_package("randomForestExplainer")
usethis::use_package("MASS")
usethis::use_package("purrr")
usethis::use_package("pdp")
usethis::use_package("ggdist")
usethis::use_package("coin")
#devtools::document()
# creation d'un fichier functions.R dans R/ --
usethis::use_r("import")
usethis::use_r("goodloop")
usethis::use_r("RUN")
usethis::use_r("moveGIF")
usethis::use_r("FastFourier")
utils::file.edit("make.R")
utils::file.edit("analyse/01_import_and_formate_data.R")
utils::file.edit("analyse/02_data_exploration.R")
utils::file.edit("analyse/03_metrics_creation.R")
utils::file.edit("analyse/04_GIF_for_angle_visualization.R")
utils::file.edit("analyse/05_ordination_forest.R")

